spring:
  application:
    name: ethereum-api

  logging:
    level:
      "com.github.tomakehurst.wiremock": "TRACE"

rpc:
  client:
    base:
      ethereum:
        url: "aHR0cHM6Ly9wYXRpZW50LWRpdmluZS1hdXJhLmV0aGVyZXVtLXNlcG9saWEucXVpa25vZGUucHJvL2M1YjNmYWZkZjE5M2M3NjExNzYxMjg5NTE3OGJmOGMwMjMwZTAzZWQ="