spring:
  application:
    name: solana-api

  logging:
    level:
      "com.github.tomakehurst.wiremock": "TRACE"

rpc:
  client:
    base:
      solana:
        url: "https://api.devnet.solana.com"