name: Codacy Coverage Reporter

on:
  push:  # Trigger on push

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: Codacy Coverage Reporter

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2

      # Step 2: Set up JDK 21 (required to run Gradle)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Run Gradle to generate coverage reports
      - name: Run tests and generate JaCoCo coverage report
        run: ./gradlew build jacocoTestReport --info

      # Step 4: Upload coverage reports to Codacy
      - name: Upload coverage reports to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: app/build/reports/jacoco/test/jacocoTestReport.xml,api/build/reports/jacoco/test/jacocoTestReport.xml
